### PR TITLE
Nucore kfs test suite

### PR DESCRIPTION
**Pull request by joshea0**
# Release Notes

Adds test suite for nucore_kfs engine

### CODE REVIEW

**Comment by joshea0** [comment]
@BenjaminNoris I believe the failing tests are due to a networking change causing the "Chart of Accounts" request to fail unless the caller is connected to the UConn VPN. This seems to be a recent change, so I'm reaching out to the KFS team to see if they know why this changed.

The tests pass locally for me when I'm connected to the VPN, so I don't think there is anything that needs to be fixed for the `chart_of_accounts_spec.rb` in this PR.

**Comment by joshea0** [comment]
@BenjaminNoris confirmed that firewall rules have been changed so those tests will not pass outside of the UConn network.

We should rewrite them to use mocked response data from the API instead.

I still want to have integration tests that hit the actual API, but we need a way to exclude them from the CI pipeline (or allow them to fail without failing the entire pipeline and blocking merging).

**Comment by BenjaminNoris** [comment]
integration tests can now be run with VPN_ENABLED=true prepended to rake command

**Comment by joshea0** [comment]
@BenjaminNoris thank you for taking care of that!

**Pull request merged**
